image:
  file: .gitpod.Dockerfile

tasks: 
  - init: >
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
    - Ikuyadeu.r
    - reditorsupport.r-lsp
    - vscode-icons-team.vscode-icons
    - ritwickdey.liveserver
    - james-yu.latex-workshop
    - dracula-theme.theme-dracula
    - enkia.tokyo-night
